manifest:
  remotes:

    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: maximoh-mmo
      url-base: https://github.com/maximoh-mmo
    - name: bullwinkle3000
      url-base: https://github.com/bullwinkle3000
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

    - name: zmk-pmw3610-driver
      remote: bullwinkle3000
      revision: pmw3360
    
    #- name: zmk-pmw3360-driver
    #  remote: maximoh-mmo
    #  revision: main
  self:
    path: config