name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
        with:
          github-token: ${{ secrets.BANANA }}